import { launch, openTool, addFiles, runAndDownload, check, summary, OUT } from './lib.mjs';
import { execFileSync } from 'node:child_process';
const { browser, page, errors } = await launch({ width: 1400, height: 1000 });
const px = (f, x, y) => JSON.parse(execFileSync('python3', ['-c', `from PIL import Image;im=Image.open('${f}').convert('RGBA');print(list(im.getpixel((${x},${y}))))`], { encoding: 'utf8' }));
const dims = (f) => JSON.parse(execFileSync('python3', ['-c', `from PIL import Image;im=Image.open('${f}');print(list(im.size))`], { encoding: 'utf8' }));
console.log('# remove-bg');
await openTool(page, 'remove-bg'); await addFiles(page, 'cutout.png'); await page.waitForSelector('.rb-cv'); await page.waitForTimeout(600); await page.screenshot({ path: OUT + '/removebg.png' });
await page.locator('label.chk', { hasText: 'Crop to the subject' }).click();
const [o] = await runAndDownload(page, '.rb-side .btn.primary.lg'); const d = dims(o); console.log('   size', d);
check('same size as source (no crop)', d[0] === 800 && d[1] === 600); check('corner transparent', px(o, 3, 3)[3] === 0); check('ellipse centre opaque red', px(o, 400, 200)[3] === 255 && px(o, 400, 200)[0] > 150); check('blue rect opaque', px(o, 400, 400)[3] === 255 && px(o, 400, 400)[2] > 150); check('outside shape transparent', px(o, 100, 300)[3] === 0);
console.log('# remove-image-watermark');
await openTool(page, 'remove-image-watermark'); await addFiles(page, 'watermarked.png'); await page.waitForSelector('.rb-cv');
const bb = await page.locator('.rb-cv').boundingBox(); await page.mouse.move(bb.x + bb.width * 0.30, bb.y + bb.height * 0.40); await page.mouse.down(); await page.mouse.move(bb.x + bb.width * 0.72, bb.y + bb.height * 0.68, { steps: 4 }); await page.mouse.up();
await page.click('button:has-text("Remove selected areas")'); await page.waitForTimeout(1500);
const [o2] = await runAndDownload(page, '.rb-side .btn.primary.lg'); const c = px(o2, 300, 200); console.log('   centre px after', c);
check('watermark text gone (centre ≈ background blue)', c[0] < 120 && c[2] > 150, JSON.stringify(c));
console.log('# thumbmark');
await openTool(page, 'thumbmark'); await addFiles(page, 'scan.png'); await page.waitForSelector('.tm-out'); await page.waitForTimeout(500); await page.screenshot({ path: OUT + '/thumb.png' });
const [o3] = await runAndDownload(page, '.tm-main .btn.primary'); const t = px(o3, 1, 1); check('thumbmark png w/ alpha', dims(o3)[0] > 20 && t[3] < 30, JSON.stringify(t));
check('no console errors', errors.filter((e) => !/Failed to load resource/.test(e)).length === 0, errors.join('\n')); await browser.close(); process.exit(summary() ? 1 : 0);
